name: Deploy to Minikube

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch. Adjust as needed.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Minikube
        run: |
          minikube start --profile=minikube
          minikube status  # Verify Minikube is running
          minikube kubectl -- get nodes  # Verify kubectl can connect to Minikube

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t lijajose/wisecow-app:$GITHUB_SHA .
          docker push lijajose/wisecow-app:$GITHUB_SHA

      - name: Deploy to Minikube
        run: |
          kubectl apply -f wisecowDeployment.yaml
          kubectl apply -f wisecowService.yaml
          kubectl apply -f wisecowIngress.yaml


     
