name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: lijajose/wisecow:latest
     - name: Deploy to Kubernetes
      uses: appleboy/k8s-deploy-action@v1.4.0
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}
        manifests: |
          k8s/wisecow-deployment.yaml
          k8s/wisecow-service.yaml
          k8s/wisecow-ingress.yaml 
