name: Deploy to Minikube

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch. Adjust as needed.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Minikube
        run: |
          minikube start --profile=minikube
          minikube status  # Verify Minikube is running
          minikube kubectl -- get nodes  # Verify kubectl can connect to Minikube

      - name: Load Docker image into Minikube
        run: |
          eval $(minikube -p minikube docker-env)
          docker build -t wisecow-app .
          docker tag wisecow-app:latest minikube:5000/wisecow-app:latest
          docker push minikube:5000/wisecow-app:latest

      - name: Deploy to Minikube
        run: |
          kubectl apply -f wisecowDeployment.yaml
          kubectl apply -f wisecowService.yaml
          kubectl apply -f wisecowIngress.yaml
