name: Deploy to Minikube

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch. Adjust as needed.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Minikube
        run: |
          minikube start --profile=minikube
          minikube status  # Verify Minikube is running
          minikube kubectl -- get nodes  # Verify kubectl can connect to Minikube
          minikube addons enable ingress  # Enable Ingress addon
          MINIKUBE_IP=$(minikube ip)  # Get Minikube IP

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t lijajose/wisecow:latest .
          docker push lijajose/wisecow:latest

      - name: Deploy to Minikube
        run: |
          kubectl apply -f wisecowDeployment.yaml
          kubectl apply -f wisecowService.yaml
          kubectl apply -f wisecowIngress.yaml

      - name: Check deployment status
        run: |
          kubectl get deployments

      - name: Check service status
        run: |
          kubectl get services

      - name: Check ingress status
        run: |
          kubectl get ingress

      - name: Access Minikube IP
        run: |
          echo "Minikube IP: $MINIKUBE_IP"
